[tool.briefcase]
project_name = "AssistantBOOTs"
bundle = "com.beatriceghetel.boots"
version = "0.0.1"
url = "https://github.com/beatriceghetel/AssistantBOOTs"
license = "Other"
author = 'Beatrice Ghetel'
author_email = "beatrice.ghetel27@gmail.com"

[tool.briefcase.app.AssistantBOOTs]
formal_name = "AssistantBOOTs"
description = "n]:"
icon = "src/AssistantBOOTs/resources/AssistantBOOTs"
sources = ['src/AssistantBOOTs']
requires = []


[tool.briefcase.app.AssistantBOOTs.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.AssistantBOOTs.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.AssistantBOOTs.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.AssistantBOOTs.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.AssistantBOOTs.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
